version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: "0000"
      MYSQL_DATABASE: capivaras_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VUE_APP_API_URL: "http://backend:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: capivaras_db
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: